baseURL = 'https://github.com/sniperreborn/testWebsite/'
languageCode = 'en-us'
theme = 'beautifulhugo-master'
title = "Taiga's Portfolio"
[params]
  homeTitle = 'Taiga Momose'
  subtitle = 'Engineering Physics Student at UBC'
  logo = 'images/Selfie.jpg'
  logoAlt = 'Taiga Momose'
  customCSS = ["css/custom.css"]
  mainSections = ["blog"]
  
  [params.author]
    name = "Taiga Momose"
    website = "https://sniperreborn.github.io/testWebsite/"  # optional, your personal website

    # Social links (these IDs must match social_icons.yml)
    linkedin = "https://www.linkedin.com/in/taiga-momose"
    email = "mailto:taigasery78@gmail.com" # optional
	
	rss = true
	disclaimerText = "All content on this site is my own work."
	
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "ResumeV11.pdf"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 4
	
  [[menu.main]]
    identifier = "courses"
    name = "Courses"
    url = "/courses/"
    weight = 5
[caches]
  [caches.images]
    dir = ':cacheDir/images'